# Generated by Django 3.2.5 on 2023-01-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newPatient2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=15, unique=True)),
                ('registered_at', models.DateField(auto_now_add=True)),
                ('patient_id', models.CharField(max_length=10, unique=True)),
                ('old_patient_id', models.CharField(max_length=50, null=True)),
                ('patient_name', models.CharField(max_length=15)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_age', models.CharField(blank=True, max_length=10, null=True)),
                ('is_deleted', models.CharField(default='N', max_length=10)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'new_patient2',
            },
        ),
    ]
