# Generated by Django 3.2.5 on 2023-01-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_newpatient2'),
    ]

    operations = [
        migrations.CreateModel(
            name='oldPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=15)),
                ('old_patient_id', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'old_patient',
            },
        ),
        migrations.DeleteModel(
            name='newPatient2',
        ),
        migrations.AlterField(
            model_name='newpatient',
            name='patient_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
