# Generated by Django 3.2.5 on 2023-01-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20230116_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='registered_at',
            field=models.DateField(),
        ),
    ]
