# Generated by Django 3.2.5 on 2023-01-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_newpatient_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='old_patient_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='newpatient',
            name='registered_at',
            field=models.DateField(),
        ),
    ]
