# Generated by Django 3.2.5 on 2023-01-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20230117_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='registered_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
