# Generated by Django 3.2.5 on 2023-01-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_newpatient_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='registered_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
