# Generated by Django 3.2.5 on 2023-01-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_newpatient_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='old_patient_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
