# Generated by Django 3.2.5 on 2023-01-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_newpatient_registered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpatient',
            name='delete_date',
        ),
    ]
