# Generated by Django 3.2.5 on 2023-01-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_remove_newpatient_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpatient',
            name='delete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
