# Generated by Django 3.2.5 on 2023-01-24 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_newpatient_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='delete_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 24, 16, 11, 27, 579579), null=True),
        ),
    ]
