# Generated by Django 3.2.5 on 2023-01-25 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_newpatient_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='delete_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 26, 20, 1, 11, 327530), null=True),
        ),
    ]
