# Generated by Django 3.2.5 on 2023-01-30 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_newpatient_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='delete_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 30, 15, 53, 15, 612417), null=True),
        ),
    ]
