# Generated by Django 3.2.5 on 2023-02-01 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_alter_newpatient_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='delete_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 1), null=True),
        ),
    ]
