# Generated by Django 3.2.5 on 2023-02-01 10:26

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_alter_newpatient_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='delete_date',
            field=models.DateField(blank=True, default=patient.models.now_plus, null=True),
        ),
    ]
