# Generated by Django 3.2.5 on 2023-02-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_alter_newpatient_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpatient',
            name='is_rejected',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='reject_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='newpatient',
            name='patient_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
