# Generated by Django 3.2.5 on 2023-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_auto_20230214_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='is_deleted',
            field=models.CharField(default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newpatient',
            name='is_rejected',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
