# Generated by Django 3.2.5 on 2023-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_auto_20230214_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpatient',
            name='is_requested',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='request_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
