# Generated by Django 3.2.5 on 2022-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SplitAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wav_filepath', models.CharField(max_length=300)),
                ('split_filename', models.CharField(max_length=100)),
                ('split_filepath', models.CharField(max_length=300)),
                ('text', models.TextField(blank=True, null=True)),
                ('start_time', models.CharField(max_length=20, null=True)),
                ('end_time', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'split_audio',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_filename', models.CharField(max_length=100)),
                ('text1', models.TextField(blank=True, default=None, null=True)),
                ('text1_user_cid', models.CharField(default=None, max_length=50, null=True)),
                ('text1_created_at', models.DateTimeField(default=None, null=True)),
                ('text1_user_mid', models.CharField(default=None, max_length=50, null=True)),
                ('text1_modified_at', models.DateTimeField(default=None, null=True)),
                ('text2', models.TextField(blank=True, default=None, null=True)),
                ('text2_user_cid', models.CharField(default=None, max_length=50, null=True)),
                ('text2_created_at', models.DateTimeField(default=None, null=True)),
                ('text2_user_mid', models.CharField(default=None, max_length=50, null=True)),
                ('text2_modified_at', models.DateTimeField(default=None, null=True)),
                ('text3', models.TextField(blank=True, default=None, null=True)),
                ('text3_user_cid', models.CharField(default=None, max_length=50, null=True)),
                ('text3_created_at', models.DateTimeField(default=None, null=True)),
                ('text3_user_mid', models.CharField(default=None, max_length=50, null=True)),
                ('text3_modified_at', models.DateTimeField(default=None, null=True)),
                ('is_requested', models.CharField(default='N', max_length=10)),
                ('is_responded', models.CharField(default=None, max_length=10, null=True)),
                ('is_deleted', models.CharField(default='N', max_length=10)),
                ('is_sound', models.CharField(default='N', max_length=10)),
                ('sound', models.CharField(default=None, max_length=40, null=True)),
                ('is_first_deleted', models.CharField(default='N', max_length=10)),
                ('is_first_sound', models.CharField(default='N', max_length=10)),
                ('first_sound', models.CharField(default=None, max_length=40, null=True)),
                ('speaker1', models.CharField(max_length=10, null=True)),
                ('speaker2', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'text',
            },
        ),
    ]
