# Generated by Django 3.2.5 on 2022-09-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitaudio',
            name='word_list',
            field=models.TextField(default=None, null=True),
        ),
    ]
