# Generated by Django 3.2.5 on 2022-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=50)),
                ('play_time', models.CharField(max_length=20)),
                ('filepath', models.CharField(max_length=300)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_age', models.CharField(max_length=10)),
                ('is_deleted', models.CharField(default='N', max_length=10)),
            ],
            options={
                'db_table': 'audio',
            },
        ),
    ]
