# Generated by Django 3.2.5 on 2022-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
