# Generated by Django 3.2.5 on 2022-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_auto_20220503_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_age', models.CharField(max_length=10)),
                ('is_deleted', models.CharField(default='N', max_length=10)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
