# Generated by Django 3.2.5 on 2022-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_audio_is_local_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='filename',
            field=models.CharField(max_length=50),
        ),
    ]
