# Generated by Django 3.2.5 on 2022-05-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_alter_audio_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='delete_reason',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
