# Generated by Django 3.2.5 on 2022-05-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_audio_delete_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
