# Generated by Django 3.2.5 on 2022-05-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_reply_rereply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
