# Generated by Django 3.2.5 on 2022-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0011_alter_reply_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='wav_filepath',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
