# Generated by Django 3.2.5 on 2022-05-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0013_alter_audio_play_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='is_split',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
