# Generated by Django 3.2.5 on 2022-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0015_splitaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitaudio',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
