# Generated by Django 3.2.5 on 2022-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0016_splitaudio_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitaudio',
            name='end_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='splitaudio',
            name='start_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
