# Generated by Django 3.2.5 on 2022-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0018_audio_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_filename', models.CharField(max_length=100)),
                ('text1', models.TextField(blank=True, default=None, null=True)),
                ('text1_user_cid', models.CharField(default=None, max_length=50, null=True)),
                ('text1_created_at', models.DateTimeField(default=None, null=True)),
                ('text1_user_mid', models.CharField(default=None, max_length=50, null=True)),
                ('text1_modified_at', models.DateTimeField(default=None, null=True)),
                ('text2', models.TextField(blank=True, default=None, null=True)),
                ('text2_user_cid', models.CharField(default=None, max_length=50, null=True)),
                ('text2_created_at', models.DateTimeField(default=None, null=True)),
                ('text2_user_mid', models.CharField(default=None, max_length=50, null=True)),
                ('text2_modified_at', models.DateTimeField(default=None, null=True)),
                ('text3', models.TextField(blank=True, default=None, null=True)),
                ('text3_user_cid', models.CharField(default=None, max_length=50, null=True)),
                ('text3_created_at', models.DateTimeField(default=None, null=True)),
                ('text3_user_mid', models.CharField(default=None, max_length=50, null=True)),
                ('text3_modified_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'text',
            },
        ),
    ]
