# Generated by Django 3.2.5 on 2022-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0021_auto_20220607_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_responded',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
