# Generated by Django 3.2.5 on 2022-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0022_text_is_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_deleted',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
