# Generated by Django 3.2.5 on 2022-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0023_text_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_sound',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='text',
            name='sound',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
