# Generated by Django 3.2.5 on 2022-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0024_auto_20220608_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_complete',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='is_responded',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
