# Generated by Django 3.2.5 on 2022-06-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0025_auto_20220608_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='is_complete',
        ),
    ]
