# Generated by Django 3.2.5 on 2022-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0026_remove_text_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='is_split',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
