# Generated by Django 3.2.5 on 2022-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0027_alter_audio_is_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='is_split',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
