# Generated by Django 3.2.5 on 2022-06-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0028_alter_audio_is_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_mod_requested',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
