# Generated by Django 3.2.5 on 2022-06-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0029_text_is_mod_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='is_mod_requested',
        ),
    ]
