# Generated by Django 3.2.5 on 2022-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0030_remove_text_is_mod_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_deleted2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='is_sound2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='sound2',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
