# Generated by Django 3.2.5 on 2022-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0031_auto_20220622_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='is_deleted2',
        ),
        migrations.RemoveField(
            model_name='text',
            name='is_sound2',
        ),
        migrations.RemoveField(
            model_name='text',
            name='sound2',
        ),
        migrations.AddField(
            model_name='text',
            name='first_sound',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='is_first_deleted',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='is_first_sound',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
