# Generated by Django 3.2.5 on 2022-06-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0032_auto_20220622_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='is_first_deleted',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='text',
            name='is_first_sound',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
