# Generated by Django 3.2.5 on 2022-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0033_auto_20220622_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='speaker',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
