# Generated by Django 3.2.5 on 2022-07-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0034_audio_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='speaker',
        ),
        migrations.AddField(
            model_name='text',
            name='speaker1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='speaker2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
