# Generated by Django 3.2.5 on 2022-08-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0035_auto_20220705_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplitAudio',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
