# Generated by Django 3.2.5 on 2022-08-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0036_auto_20220817_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='ReReply',
        ),
    ]
