# Generated by Django 3.2.5 on 2022-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0037_auto_20220817_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='prev_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
