# Generated by Django 3.2.5 on 2023-01-06 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0038_audio_prev_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_code', models.CharField(max_length=30)),
                ('doctor_id', models.CharField(max_length=15)),
                ('doctor_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='d_code',
            field=models.CharField(default=998, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='doctor_id',
            field=models.CharField(default=998, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='new_patient_id',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='reg_id',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
