# Generated by Django 3.2.5 on 2023-01-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0039_auto_20230106_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='d_code',
            field=models.CharField(default='998', max_length=30),
        ),
        migrations.AlterField(
            model_name='audio',
            name='doctor_id',
            field=models.CharField(default='998-01', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(default='noname', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reg_id',
            field=models.CharField(default='00000000', max_length=15),
        ),
    ]
