# Generated by Django 3.2.5 on 2023-01-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0041_audio_new_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='newPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=15)),
                ('registered_at', models.DateField(auto_now_add=True)),
                ('patient_id', models.CharField(max_length=10)),
                ('patient_name', models.CharField(max_length=15)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_age', models.CharField(max_length=10)),
                ('is_deleted', models.CharField(default='N', max_length=10)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'new_patient',
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='reg_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registered_at',
        ),
    ]
