# Generated by Django 3.2.5 on 2023-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0042_auto_20230109_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpatient',
            name='patient_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='newpatient',
            name='reg_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
