# Generated by Django 3.2.5 on 2023-01-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0045_alter_newpatient_patient_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newPatient',
        ),
    ]
