# Generated by Django 3.2.5 on 2023-02-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0047_remove_audio_new_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='new_patient_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='reg_id',
            field=models.CharField(default='00000000', max_length=15),
        ),
    ]
