# Generated by Django 3.2.5 on 2023-02-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0048_auto_20230206_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='reg_id',
        ),
    ]
