# Generated by Django 3.2.5 on 2022-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('d_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.TextField()),
                ('d_code', models.CharField(max_length=30)),
                ('is_admin', models.CharField(default='N', max_length=10)),
                ('registered_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
