# Generated by Django 3.2.5 on 2022-05-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_d_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('c_name', models.CharField(max_length=30, unique=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
