# Generated by Django 3.2.5 on 2022-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_company_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_admin',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
