# Generated by Django 3.2.5 on 2022-05-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_request_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c_code',
            field=models.CharField(default='01', max_length=30),
            preserve_default=False,
        ),
    ]
